### ISSUE TITLE
Specializing commands

### ISSUE THREAD

**Issue by saucisson** [CosyVerif/paquito#42]
Is it possible to specialize commands? For instance, to build [etienneandre/imitator](https://github.com/etienneandre/imitator):

``` yaml
Packages:
    imitator:
        ...
        Build:
            ...
            Commands:
                - ppl-source:
                  Debian: apt-get source libppl-dev
                  Arch: ???
                - cd ppl-1.1/
                ...
```
