### ISSUE TITLE
Dependencies do not allow lists within system specialization

### ISSUE THREAD

**Issue by saucisson** [CosyVerif/paquito#50]
For instance,

``` yaml
                php-cli:
                    Debian:
                        All: php5-cli
                    Archlinux:
                        All: php-cgi
                    Centos:
                        All:
                            - php-xml
                            - php-process
```
