### ISSUE TITLE
Is it possible to avoid "All:" in dependencies?

### ISSUE THREAD

**Issue by saucisson** [CosyVerif/paquito#51]
For instance:

``` yaml
                devel:
                    Debian: build-essential
                    Centos: rpmdevtools
                    Archlinux: <none>
```
